# Site settings
title: "Cat's Whiskers"
email: okamoto.yuki.0130@gmail.com
description: "岡本 悠希について"
baseurl: "https://blog.okamotoyuki.me"
url: "https://blog.okamotoyuki.me"
title_description: "ソフトウェア技術、ライフハック、働き方などをテーマにブログを書いてます。
                    本サイトが、情報発信だけではなく議論の場にもなればと考えているので、
                    コメントやフィードバック等あれば、是非いただければ幸いです。
                    なお、ブログ上での発言はあくまで個人的な意見であり、著者の所属する組織の公式見解ではありません。"
title_image: "https://s.gravatar.com/avatar/092c28f1060cd991615c5d1e5eac5841?s=400"
author: "Yuki Okamoto"
author_description: "Atlassian のシニアテクニカルサポートエンジニア。認定スクラムマスター。
                    Accenture にて、某金融機関の営業支援システム開発プロジェクトにおける
                    構成管理に関する技術提案等に携わった後、2015年6月より現職。
                    Atlassian 日本法人における技術サポートチームの拡大、
                    Atlassian 製品・ドキュメントの国際化に貢献する。"
author_avatar: "https://s.gravatar.com/avatar/092c28f1060cd991615c5d1e5eac5841?s=400"
google_analytics: "UA-70511107-2"
disqus_account: yuki_okamoto
# github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-59b3a6d3530cb2b6
post_limit: 5

# Social usernames/URLs
twitter_username: okmt_uk
github_username:  okamotoyuki
instagram_username: 0kam0t0yuk1
reddit_username:
linkedin_link: https://www.linkedin.com/in/%E6%82%A0%E5%B8%8C-%E5%B2%A1%E6%9C%AC-13b64b72/
# google_plus_link: https://plus.google.com/u/0/113918174047947597063
stackoverflow_link:
xing_link:
facebook_link: https://www.facebook.com/yuki.okamoto.756

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title/
exclude: [vendor]

future: true
